os: linux
dist: xenial
language: node_js
node_js: 13
cache: npm

script:
  - node -v
  - npm -v
  - npm install
  - npm run build

deploy:
  provider: pages
  strategy: git
  local_dir: public
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: false
  target_branch: master
  on:
    branch: blog
